#include <iostream>

using namespace std;

const double PI = 3.14159265358979323846264338327950288;

/*
    3. C++ Constructors
*/

class Cylinder {

    // Properties
    private:
        double height;
        double radius;

    // Behaviours
    public:
        Cylinder() {
            radius = 2.0;
            height = 2.0;
        }

        Cylinder(double radiusParam, double heightParam) {
            radius = radiusParam;
            height = heightParam;
        }

        double volume() {
            return PI * radius * radius * height;
        }
};

/*
    Constructor Definition:

    A constructor is a special member function in object-oriented programming languages that is responsible for initializing objects of a class. 
    It is called automatically when an instance(object) of a class is created or instantiated.

    The constructor has the same name as the class and does not have a return type, not even void. 
    It is used to set the initial state of an object by initializing its member variables or performing other necessary setup tasks.

    1. Initialization: The primary purpose of a constructor is to initialize the member variables of an object. 
    It assigns initial values to the object's data members, ensuring that the object is in a valid and usable state when it is created.
    (like in functions).

    2. Automatic Invocation: Constructors are automatically invoked when an object is created using the new keyword or when it is declared as a local variable. 
    The constructor is called implicitly, without the need for explicit function calls.

    3. Same Name as Class: Constructors have the same name as the class they belong to. 
    This allows the compiler to identify and associate the constructor with the corresponding class.

    4. Overloading: Constructors can be overloaded, meaning a class can have multiple constructors with different parameter lists. 
    This allows objects to be created with different initializations depending on the arguments passed during object creation.

    5. No Return Type: Constructors do not have a return type, not even void. 
    They are automatically invoked during object creation and do not return any value.

    6. Optional: Constructors are not mandatory for a class. If a class does not define any constructors,
    the compiler provides a default constructor that initializes the member variables with default values 
    (e.g., zero for numeric types, null for reference types).

    By using constructors, the process of object creation becomes controlled, ensuring proper initialization and encapsulation of object state. 
    Constructors play a vital role in object-oriented programming as they allow for the initialization of objects and provide a means to set up their initial state.
*/



/*
    An example of a need constructor in a real software project:

    Let's consider a real software project, such as a customer relationship management (CRM) system. 
    In this CRM system, we can have a class called "Customer" that represents individual customers and stores their information.

    Here's an example of how constructors can be used in this scenario:
*/

class Customer {
    private:
        string name;
        string email;
        string phoneNumber;

    public:
        // Default constructor
        Customer() {
            // Set default values
            name = "";
            email = "";
            phoneNumber = "+994";
        }

        // Constructor with parameters
        Customer(string nameP, string emailP, string phoneNumberP) {
            name = nameP;
            email = emailP;
            phoneNumber = phoneNumberP;
        }

    // Other methods...    
};


int main() {

    // automatically calls default constructor
    Cylinder cylender1;

    cout << "volume 1: " << cylender1.volume() << endl;


    // Overloads constructor by taking parameters
    Cylinder cylender2(10, 4);

    cout << "volume 2: " << cylender2.volume() << endl;

    /*
        When a class doesn't have a constructor declared, the compiler will still generate a default 
        empty constructor if we create an instance of that class.

        Ex:

        // Default constructor generated by compiler
        Cylinder() {}
    */



    /*
        These constructors enable flexibility when creating instances of the "Customer" class. 
        You can use the default constructor when you need to create a customer object 
        with default values and set the specific values later using setter methods. 
        Alternatively, you can use the constructor with parameters to create a customer object with specific information directly.
    */

    Customer customer1();    // Create a customer with default values
    Customer customer2("John Doe", "johndoe@example.com", "123456789");    // Create a customer with specific values


}
