#include <iostream>

using namespace std;

const double PI = 3.14159265358979323846264338327950288;

/*
    4. Defaulted Constructors
*/

class Cylinder {

    // Properties
    private:
        double height;
        double radius;

    // Behaviours
    public:
        // Cylinder() = default;

        // defaulted constructor
        Cylinder() {
            radius = 1;
            height = 1;
        }

        Cylinder(double radiusParam, double heightParam) {
            radius = radiusParam;
            height = heightParam;
        }

        double volume() {
            return PI * radius * radius * height;
        }
};



/*
    In C++, a defaulted constructor is a special constructor that is automatically generated by the compiler when certain conditions are met. 
    
    A defaulted constructor behaves similarly to an explicitly defined default constructor, 
    but its implementation is provided by the compiler.

    A constructor can be defaulted by using the default keyword in the constructor declaration. 

    When a constructor is defaulted, the compiler generates the necessary code for initializing the object's data members. 
    The defaulted constructor is typically used when the default initialization behavior is sufficient for the class.
*/

// Note: constructors have to be declared as public if they are intended to be used outside of the class.



int main() {

    /*
        If a constructor is explicitly declared in a class, the compiler will not generate an empty constructor
        because it recognizes the presence of the declared constructor.
    */
    Cylinder cylender1;

    cout << "volume 1: " << cylender1.volume() << endl;


    // Overloads constructor by taking parameters
    Cylinder cylender2(10, 4);
}
